spring:
  data:
    mongodb:
      authentication-database: admin
      username: user
      password: password
      database: omsDB
      port: 3307
      host: localhost
  mail:
    host: smtp.gmail.com
    port: 587
    username: oms.reset.service@gmail.com
    password: pcbwvxwbcsxtxolb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.springframework.mail: DEBUG


application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days


